---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Ensure a broken PPA is deleted.
      file:
        path: /etc/apt/sources.list.d/jonathonf-python-2_7-trusty.list
        state: absent
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_version == '14.04'

    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Ensure build dependencies are installed.
      package:
        name:
          - openssh-client
          - openssh-server
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - role: tsukune_ch.canonical_livepatch
