---
name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '0 5 * * 5'
defaults:
  run:
    working-directory: 'tsukune_ch.canonical_livepatch'
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: 'tsukune_ch.canonical_livepatch'
      - name: Setup python 3.x.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: >
          pip3 install
          ansible
          ansible-lint
          yamllint
      - name: Lint code.
        run: |
          yamllint .
          ansible-lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: 'tsukune_ch.canonical_livepatch'
      - name: Setup python 3.x.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: >
          pip3 install
          ansible
          docker
          'molecule[docker]>=3.2.3,<4.0'
      - name: Run Molecule tests.
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          molecule test
