---
name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '0 5 * * 5'
jobs:
  lint:
    runs-on: ubuntu-20.04
    env:
      ROLE_NAME: canonical_livepatch
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: "tsukune_ch.${{ env.ROLE_NAME }}"
      - name: Setup python 3.x.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: >
          pip3 install
          ansible
          ansible-lint
          yamllint
      - name: Lint code.
        run: |
          yamllint .
          ansible-lint
        working-directory: "tsukune_ch.${{ env.ROLE_NAME }}"
  test:
    runs-on: ubuntu-20.04
    env:
      ROLE_NAME: canonical_livepatch
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: "tsukune_ch.${{ env.ROLE_NAME }}"
      - name: Setup python 3.x.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: >
          pip3 install
          ansible
          ansible-lint
          docker
          flake8
          'molecule[docker]>=3.0.2.1,<4.0'
          yamllint
      - name: Run Molecule tests.
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          molecule test
        working-directory: "tsukune_ch.${{ env.ROLE_NAME }}"
