---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization secret.

name: Release
on:
  push:
    tags:
      - '*'
defaults:
  run:
    working-directory: 'tsukune_ch.canonical_livepatch'
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: 'tsukune_ch.canonical_livepatch'
      - name: Setup python 3.x.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible.
        run: |
          pip3 install ansible-base
      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1)
          $(echo ${{ github.repository }} | cut -d/ -f2)
